package it.kirey.kfuture.entity;
// Generated 14-Oct-2016 10:47:00 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AmProducts generated by hbm2java
 */
@Entity
@Table(name = "AM_PRODUCTS", uniqueConstraints = @UniqueConstraint(columnNames = "NAME_GENERIC_NAME"))
public class AmProducts implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String nameGenericName;
	private Long minAmount;
	private Long lifecycle;

	public AmProducts() {
	}

	public AmProducts(Integer id, String nameGenericName) {
		this.id = id;
		this.nameGenericName = nameGenericName;
	}

	public AmProducts(Integer id, String nameGenericName, Long minAmount, Long lifecycle) {
		this.id = id;
		this.nameGenericName = nameGenericName;
		this.minAmount = minAmount;
		this.lifecycle = lifecycle;
	}

	@Id
	@SequenceGenerator(name = "prod_gen", sequenceName = "SEQ_AM_PRODUCTS", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "prod_gen")
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME_GENERIC_NAME", unique = true, nullable = false)
	public String getNameGenericName() {
		return this.nameGenericName;
	}

	public void setNameGenericName(String nameGenericName) {
		this.nameGenericName = nameGenericName;
	}

	@Column(name = "MIN_AMOUNT", precision = 22, scale = 0)
	public Long getMinAmount() {
		return this.minAmount;
	}

	public void setMinAmount(Long minAmount) {
		this.minAmount = minAmount;
	}

	@Column(name = "LIFECYCLE", precision = 1, scale = 0)
	public Long getLifecycle() {
		return this.lifecycle;
	}

	public void setLifecycle(Long lifecycle) {
		this.lifecycle = lifecycle;
	}

}
