package it.kirey.kfuture.entity;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CoreConfConfigs generated by hbm2java
 */
@Entity
@Table(name = "batch_configs")
public class BatchConfigs implements java.io.Serializable {

	private static final long serialVersionUID = -1077525675212778805L;

	private BatchConfigsId id;
	private String parameter;


	public BatchConfigs() {
		}

	public BatchConfigs(BatchConfigsId id, String parameter) {
			this.id = id;
			this.parameter = parameter;
		}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "value", column = @Column(name = "value", nullable = false, length = 25)),
			@AttributeOverride(name = "category", column = @Column(name = "category", nullable = false, length = 25)) })
	public BatchConfigsId getId() {
		return this.id;
	}

	public void setId(BatchConfigsId id) {
		this.id = id;
	}

	@Column(name = "parameter", nullable = false, length = 128)
	public String getParameter() {
		return this.parameter;
	}

	public void setParameter(String parameter) {
		this.parameter = parameter;
	}

}
